name: autoupdater
run-name: autoupdater
on:
  push:
  schedule:
    - cron:  '35 3 * * 0'  # every Sunday at 03:35

jobs:
  python_script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          token: ${{ secrets.PAT }}

      - uses: actions/setup-python@v6
        with:
          python-version: '3.13'
          cache: 'pip' # caching pip dependencies

      - run: pip install -r requirements.txt
      - run: python updater.py

      - name: Push generated files to target repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.PAT }}
        with:
          source-directory: '_work'
          destination-github-username: 'rnckp'
          destination-repository-name: 'starter-code_opendataswiss'
          target-branch: main
          commit-message: "Updates"
          
